//This file was generated by script mkregs.py

//register address mapping
#define ILA_SOFTRESET 0
#define ILA_TRIGGER_TYPE 1
#define ILA_TRIGGER_NEGATE 2
#define ILA_TRIGGER_MASK 3
#define ILA_DELAY_TRIGGER 4
#define ILA_DELAY_SIGNAL 5
#define ILA_REDUCE_TYPE 6
#define ILA_INDEX 7
#define ILA_SIGNAL_SELECT 8
#define ILA_SPECIAL_TRIGGER_MASK 9
#define ILA_DATA 10
#define ILA_SAMPLES 11
#define ILA_CURRENT_DATA 12
#define ILA_CURRENT_TRIGGERS 13
#define ILA_CURRENT_ACTIVE_TRIGGERS 14
