//This file was generated by script mkregs.py

//register address mapping
#define ILA_MISCELLANEOUS 0
#define ILA_TRIGGER_TYPE 1
#define ILA_TRIGGER_NEGATE 2
#define ILA_TRIGGER_MASK 3
#define ILA_INDEX 4
#define ILA_SIGNAL_SELECT 5
#define ILA_DATA 6
#define ILA_SAMPLES 7
#define ILA_CURRENT_DATA 8
#define ILA_CURRENT_TRIGGERS 9
#define ILA_CURRENT_ACTIVE_TRIGGERS 10
#define ILA_STATUS 11
